---
name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu:latest
    name: Publish site
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: www.ultimate-thorigne-fouillard.fr
